#!/usr/bin/env python2
from __future__ import print_function
import contextlib
import shutil
import subprocess
import os
import os.path
import sys

@contextlib.contextmanager
def chdir(path):
    original = os.getcwd()
    os.chdir(path)
    try:
        yield
    finally:
        os.chdir(original)

def test_compiler():
    with chdir('compiler'):
        subprocess.check_call(['pulp', 'test'])

def build_purescript_support():
    with chdir('purescript'):
        subprocess.check_call(['pulp', 'build'])

def test_cases():
    for case in {os.path.splitext(p)[0] for p in os.listdir('test/cases')}:
        print(case)

        tdl_path = 'test/cases/{}.tdl' .format(case)
        ps_path  = 'test/cases/{}.purs'.format(case)

        tmp_path = '/tmp/TDLCase{}'.format(case)
        try:
            os.mkdir(tmp_path)
        except:
            pass

        shutil.copyfile(ps_path, '{}/Main.purs'.format(tmp_path))
        tdl_output = subprocess.check_output(['compiler/bin/tdlc', tdl_path])
        with open('{}/TDLOutput.purs'.format(tmp_path), 'w') as f:
            print('module TDLOutput where', file=f)
            print(tdl_output, file=f)

        with chdir('purescript'):
            subprocess.check_call([
                'pulp', 'build',
                '-o', '{}/output'.format(tmp_path),
                '-I', tmp_path,
            ])

        with chdir(tmp_path):
            script = '''
                var Main = require('./output/Main');
                var status = 0;
                for (var prop in Main) {
                    console.log(prop);
                    var ok = Main[prop]();
                    status = ok ? status : 1;
                    console.log('  - ' + ok);
                }
                process.exit(status);
            '''
            subprocess.check_call(['node', '-e', script])

def bower_install(path):
    with chdir(path):
        subprocess.check_call(['bower', 'install'])

def main():
    test_compiler()
    build_purescript_support()
    test_cases()

if __name__ == '__main__':
    if ('--with-bower-install' in sys.argv):
        bower_install('compiler')
        bower_install('purescript')
    main()
